function p = A(p_l,v_l,v_0,v_n,d)
%A
%    P = A(P_L,V_L,V_0,V_N,D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    20-Apr-2016 10:17:10

p = p_l+v_l.*9.35e5-v_n.*9.35e5-5.0.^(3.0./4.0).*1.0./d.^(5.0./4.0).*v_l.*abs(v_l).^(3.0./4.0).*1.07576e4;
