function p = B(p_r,v_r,v_n,d)
%B
%    P = B(P_R,V_R,V_N,D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    08-Apr-2016 17:22:40

p = p_r+v_n.*9.35e5-v_r.*9.35e5+1.0e1.^(3.0./4.0).*1.0./d.^(5.0./4.0).*v_r.*abs(v_r).^(3.0./4.0).*5.3788e3;
