function nextLine = reduce(this)
	
	p = this.pressure;
	v = this.velocity;
	d = this.diameter;

	[p v] = reducers.AB( ...
		p(1:end - 2), ...
		p(3:end), ...
		v(1:end - 2), ...
		v(3:end), ...
		d);

	nextLine = Line(this);
	nextLine.pressure = [NaN p NaN];
	nextLine.velocity = [NaN v NaN];
